# Generated by Django 5.2.4 on 2025-12-20 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citizen_repo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NationalIDRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('chief_verified', 'Chief Verified'), ('submitted_to_nrb', 'Submitted to NRB'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='initiated', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_to_nrb_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='id_requests', to='citizen_repo.citizen')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id_requests_as_father', to='citizen_repo.citizen')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_requests_initiated', to=settings.AUTH_USER_MODEL)),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='id_requests_as_mother', to='citizen_repo.citizen')),
                ('verified_by_chief', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_requests_verified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
