# Generated by Django 5.2.8 on 2025-12-14 21:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("geography", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Citizen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_number",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("first_name", models.CharField(max_length=100)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("date_of_birth", models.DateField()),
                ("place_of_birth", models.CharField(max_length=255)),
                (
                    "father_id_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "mother_id_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("is_alive", models.BooleanField(default=True)),
                ("date_of_death", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="citizens",
                        to="geography.area",
                    ),
                ),
            ],
            options={
                "verbose_name": "Citizen",
                "verbose_name_plural": "Citizens",
                "ordering": ["id_number"],
            },
        ),
        migrations.CreateModel(
            name="CitizenQueryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_number_queried", models.CharField(max_length=20)),
                ("last_name_provided", models.CharField(blank=True, max_length=100)),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("birth", "Birth Registration"),
                            ("death", "Death Registration"),
                            ("marriage", "Marriage Registration"),
                            ("general", "General Lookup"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("was_found", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="citizen_queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
