# Generated by Django 5.2.4 on 2025-12-30 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen_repo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='id_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
    ]
