# Generated by Django 5.2.4 on 2025-12-30 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen_repo', '0002_alter_citizen_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizenquerylog',
            name='id_number_queried',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
