# Generated by Django 5.2.4 on 2025-12-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen_repo', '0003_alter_citizenquerylog_id_number_queried'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizenquerylog',
            name='last_name_provided',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
