# Generated by Django 5.2.4 on 2026-01-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen_repo', '0004_alter_citizenquerylog_last_name_provided'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='id_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
