# Generated by Django 5.2.4 on 2025-12-24 04:48

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('area_type', models.CharField(choices=[('country', 'Country'), ('region', 'Region'), ('county', 'County'), ('sub_county', 'Sub County'), ('division', 'Division'), ('location', 'Location'), ('sub_location', 'Sub Location'), ('village', 'Village')], max_length=20)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, help_text='Administrative boundary (Leaflet-ready)', null=True, srid=4326)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant_chief', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_chief_areas', to=settings.AUTH_USER_MODEL)),
                ('chief', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chief_areas', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='geography.area')),
            ],
            options={
                'indexes': [models.Index(fields=['area_type'], name='geography_a_area_ty_78242c_idx'), models.Index(fields=['latitude', 'longitude'], name='geography_a_latitud_cd14ce_idx')],
                'unique_together': {('parent', 'name', 'area_type')},
            },
        ),
    ]
