# Regions
REGION_CODES = {
    "Nairobi Region": "01",
    "Central Region": "02",
    "Rift Valley Region": "03",
    "Nyanza Region": "04",
    "Coast Region": "05",
    "Eastern Region": "06",
    "North Eastern Region": "07",
    "Western Region": "08",
}

# Counties (official 001–047)
COUNTY_CODES = {
    "Mombasa County": "001",
    "Kwale County": "002",
    "Kilifi County": "003",
    "Tana River County": "004",
    "Lamu County": "005",
    "Taita Taveta County": "006",
    "Garissa County": "007",
    "Wajir County": "008",
    "Mandera County": "009",
    "Marsabit County": "010",
    "Isiolo County": "011",
    "Meru County": "012",
    "Tharaka Nithi County": "013",
    "Embu County": "014",
    "Kitui County": "015",
    "Machakos County": "016",
    "Makueni County": "017",
    "Nyandarua County": "018",
    "Nyeri County": "019",
    "Kirinyaga County": "020",
    "Murang'a County": "021",
    "Kiambu County": "022",
    "Turkana County": "023",
    "West Pokot County": "024",
    "Samburu County": "025",
    "Trans Nzoia County": "026",
    "Uasin Gishu County": "027",
    "Elgeyo Marakwet County": "028",
    "Nandi County": "029",
    "Baringo County": "030",
    "Laikipia County": "031",
    "Nakuru County": "032",
    "Narok County": "033",
    "Kajiado County": "034",
    "Kericho County": "035",
    "Bomet County": "036",
    "Kakamega County": "037",
    "Vihiga County": "038",
    "Bungoma County": "039",
    "Busia County": "040",
    "Siaya County": "041",
    "Kisumu County": "042",
    "Homa Bay County": "043",
    "Migori County": "044",
    "Kisii County": "045",
    "Nyamira County": "046",
    "Nairobi County": "047",
}
