# Generated by Django 5.2.4 on 2025-12-24 04:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citizen_repo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('place_of_birth', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('reference_number', models.CharField(max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birth_record', to='citizen_repo.citizen')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='births_as_father', to='citizen_repo.citizen')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='births_initiated', to=settings.AUTH_USER_MODEL)),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='births_as_mother', to='citizen_repo.citizen')),
            ],
        ),
        migrations.CreateModel(
            name='DeathRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_of_death', models.DateField()),
                ('place_of_death', models.CharField(max_length=255)),
                ('cause_of_death', models.TextField(blank=True)),
                ('reference_number', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='death_records', to='citizen_repo.citizen')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarriageRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_of_marriage', models.DateField()),
                ('place_of_marriage', models.CharField(max_length=255)),
                ('reference_number', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('spouse_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marriages_as_spouse1', to='citizen_repo.citizen')),
                ('spouse_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marriages_as_spouse2', to='citizen_repo.citizen')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=30, unique=True)),
                ('registration_type', models.CharField(choices=[('birth', 'Birth'), ('death', 'Death'), ('marriage', 'Marriage')], max_length=20)),
                ('citizen_first_name', models.CharField(max_length=100)),
                ('citizen_middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('citizen_last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('mother_id_number', models.CharField(max_length=20)),
                ('father_id_number', models.CharField(blank=True, max_length=20, null=True)),
                ('mother_verified', models.BooleanField(default=False)),
                ('father_verified', models.BooleanField(default=False)),
                ('chief_verification_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending_verification', 'Pending Chief Verification'), ('pending_nrb', 'Pending NRB Registration'), ('completed', 'Completed')], default='pending_verification', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_requests', to=settings.AUTH_USER_MODEL)),
                ('verified_by_chief', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
