# Generated by Django 5.2.4 on 2025-12-26 09:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deathregistration',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
