# Generated by Django 5.2.4 on 2025-12-29 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_registration', '0002_deathregistration_created_at'),
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthregistration',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geography.area'),
        ),
        migrations.AddField(
            model_name='deathregistration',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geography.area'),
        ),
        migrations.AddField(
            model_name='marriageregistration',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geography.area'),
        ),
        migrations.AddField(
            model_name='marriageregistration',
            name='venue_of_marriage',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geography.area'),
        ),
    ]
