# Generated by Django 5.2.4 on 2025-12-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_registration', '0003_birthregistration_area_deathregistration_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deathregistration',
            name='age',
            field=models.BigIntegerField(default=0),
        ),
    ]
