# Generated by Django 5.2.4 on 2026-01-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_registration', '0004_deathregistration_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='deathregistration',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
