# Generated by Django 5.2.8 on 2025-12-08 17:16

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True,
                        help_text="Optional polygon for the administrative boundary",
                        null=True,
                        srid=4326,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdminUnit",
            fields=[
                (
                    "UID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Official name of unit (e.g., Nairobi County)",
                        max_length=255,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Optional unit code (e.g., KE-47-001)",
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("CS", "Cabinet Secretary"),
                            ("PS", "Principal Secretary"),
                            ("RC", "Region"),
                            ("CC", "County"),
                            ("DCC", "Sub-County"),
                            ("ACC", "Division"),
                            ("CHIEF", "Location"),
                            ("ASST_CHIEF", "Sub-Location"),
                            ("WARD", "Ward"),
                            ("LOCATION", "Location"),
                            ("SUB_LOCATION", "Sub-location"),
                        ],
                        default="LOCATION",
                        max_length=24,
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True,
                        help_text="Polygon or point for administrative boundary/location.",
                        null=True,
                        srid=4326,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent administrative unit.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="admin_structure.adminunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Administrative Unit",
                "verbose_name_plural": "Administrative Units",
                "ordering": ("level", "name"),
                "indexes": [
                    models.Index(fields=["code"], name="admin_struc_code_892823_idx"),
                    django.contrib.postgres.indexes.BrinIndex(
                        fields=["created_at"], name="admin_struc_created_3d4134_brin"
                    ),
                ],
            },
        ),
    ]
