# Generated by Django 5.2.4 on 2025-12-29 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officerprofile',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas', to='geography.area'),
        ),
    ]
