# Generated by Django 5.2.8 on 2025-12-08 17:16

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admin_structure", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Title of Incident"),
                ),
                ("description", models.TextField(verbose_name="Detailed Description")),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("fire", "Fire Incident"),
                            ("accident", "Traffic Accident"),
                            ("crime", "Crime/Security"),
                            ("medical", "Medical Emergency"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reported", "Reported"),
                            ("dispatched", "Dispatched"),
                            ("on_scene", "On Scene"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="reported",
                        max_length=50,
                    ),
                ),
                (
                    "coordinates",
                    django.contrib.gis.db.models.fields.PointField(
                        default=django.contrib.gis.geos.point.Point(0.0, 0.0),
                        srid=4326,
                        verbose_name="Geospatial Coordinates",
                    ),
                ),
                (
                    "date_reported",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date Reported"
                    ),
                ),
                (
                    "date_resolved",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date Resolved"
                    ),
                ),
                (
                    "current_handler",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_incidents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Current Handler",
                    ),
                ),
                (
                    "handlers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assigned_incidents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Handlers",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        default="00000000-0000-0000-0000-000000000001",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents",
                        to="admin_structure.adminunit",
                        verbose_name="Administrative Location Unit",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents_reported",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reported By User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Incident",
                "verbose_name_plural": "Incidents",
                "ordering": ["-date_reported"],
            },
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="incidents.incident",
                    ),
                ),
                (
                    "responder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(
                fields=["incident_type"], name="incidents_i_inciden_337dba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(fields=["status"], name="incidents_i_status_9a4f12_idx"),
        ),
    ]
