# Generated by Django 5.2.8 on 2025-12-14 01:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0001_initial"),
        ("incidents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incidents",
                to="geography.area",
                verbose_name="Geographic Area",
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="reported_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="incident",
            name="reporter_phone",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
