# Generated by Django 5.2.4 on 2025-12-29 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
        ('incidents', '0002_alter_incident_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='geography.area', verbose_name='Geographic Area'),
        ),
    ]
