# Generated by Django 5.2.4 on 2025-12-31 08:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_alter_incident_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='reporter_email',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='reporter_id_number',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='reporter_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='reporter_statement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('reported', 'Reported'), ('dispatched', 'Dispatched'), ('on_scene', 'On Scene'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('urgent', 'Urgent')], default='reported', max_length=50),
        ),
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, null=True)),
                ('statement', models.TextField(blank=True, null=True)),
                ('id_number', models.CharField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.incident')),
            ],
        ),
        migrations.AddField(
            model_name='incident',
            name='witnesses',
            field=models.ManyToManyField(blank=True, related_name='witnesses', to='incidents.witness'),
        ),
    ]
