# Generated by Django 5.2.4 on 2025-12-31 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_incident_reporter_email_incident_reporter_id_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='witnesses',
        ),
        migrations.AlterField(
            model_name='witness',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witnesses', to='incidents.incident'),
        ),
    ]
